### ISSUE TITLE
[提议]支持scoresaber网站的分数查询

### ISSUE THREAD

**Issue by Agnes4m** [qwq12738qwq/nonebot-plugin-beatsaberscore#1]
[scoresaber](https://scoresaber.com/rankings)

**Comment by qwq12738qwq** [comment]
> [scoresaber](https://scoresaber.com/rankings)

OK,不过我已经国庆收假了，给我些时间，等学校放假我再着手这件事

**Comment by qwq12738qwq** [comment]
> [评分剑士](https://scoresaber.com/rankings)

更新力
