### ISSUE TITLE
BL信息无法获取

### ISSUE THREAD

**Issue by Agnes4m** [qwq12738qwq/nonebot-plugin-beatsaberscore#2]
在0.9.6版本下，绑定会显示无法获取，但是在0.9.0之前的版本是没有问题的
![image](https://github.com/user-attachments/assets/c98a666a-bed8-4435-9230-575653ea5244)

同时在网站中也是能正确搜索到的
![image](https://github.com/user-attachments/assets/648ec2a9-df39-4005-9a25-dc31377403b8)

**Comment by qwq12738qwq** [comment]
OK,我去看看

**Comment by qwq12738qwq** [comment]
> 在0.9.6版本下，绑定会显示无法获取，但是在0.9.0之前的版本是没有问题的 ![image](https://private-user-images.githubusercontent.com/70925546/373928258-c98a666a-bed8-4435-9230-575653ea5244.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyMDcxOTksIm5iZiI6MTcyODIwNjg5OSwicGF0aCI6Ii83MDkyNTU0Ni8zNzM5MjgyNTgtYzk4YTY2NmEtYmVkOC00NDM1LTkyMzAtNTc1NjUzZWE1MjQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA2VDA5MjgxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkMDE4ODhlOGY5MjU4YWJmNmE1NTM0NTEwODA1MmRkZjcyYzFlNzlmODY0ZTAyZWI5NmY4ZmY2NGIyNjFkZDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.WKE1tqTvxWPT3ZH5v7c-7P46LyMVJdWaCLdHgG1kTyY)
> 
> 同时在网站中也是能正确搜索到的 ![image](https://private-user-images.githubusercontent.com/70925546/373928301-648ec2a9-df39-4005-9a25-dc31377403b8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyMDcxOTksIm5iZiI6MTcyODIwNjg5OSwicGF0aCI6Ii83MDkyNTU0Ni8zNzM5MjgzMDEtNjQ4ZWMyYTktZGYzOS00MDA1LTlhMjUtZGMzMTM3NzQwM2I4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA2VDA5MjgxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzZTRkYTQ2NjRlMmEyNjQwYmRjNDIzYTJkNmIzOThhNmIyZWRhZmE4NjNjN2E5MTFmY2M2MDIxOTA1MDNmOWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.-73mxecI4a03ZubVEkNPk0gFhN4V0U8nN1fZ7I4tBYQ)

修改好了,你试一下?正常的话就说一声吧

**Comment by Agnes4m** [comment]
发送BS绑定信息，在获取信息时报错
![image](https://github.com/user-attachments/assets/a056eca0-3636-4764-be78-83032ead3cd4)

**Comment by qwq12738qwq** [comment]
> 发送BS绑定信息，在获取信息时报错 ![image](https://private-user-images.githubusercontent.com/70925546/374041258-a056eca0-3636-4764-be78-83032ead3cd4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzMTIwMzcsIm5iZiI6MTcyODMxMTczNywicGF0aCI6Ii83MDkyNTU0Ni8zNzQwNDEyNTgtYTA1NmVjYTAtMzYzNi00NzY0LWJlNzgtODMwMzJlYWQzY2Q0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA3VDE0MzUzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQzOWFjMzMwYmY1ZWI0ZDVmNjZlOTI0NGY1ODFjMmM2ZGUwYzdhNTJkMTQ2ZjQyOTk2OTQ4Njc4OTRiOWU5MTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.3FTGEnyQ3GHzMeX_azYPPENuhsVtSnXiEqfMM8t5q2o)

脑子瓦特了忘记给变量赋值了,现在已经更新力,请大佬帮我测试一下罢QAQ

**Comment by Agnes4m** [comment]
同报错，建议测试好了再git push
![image](https://github.com/user-attachments/assets/18eb1b85-8fb2-4d05-a3be-ad837f2aa564)

**Comment by qwq12738qwq** [comment]
github的库更新力，当时只是更新了pypi库(还不太会用guyhub，想着放假再把源码上传的)
![QQ图片20241011191654](https://github.com/user-attachments/assets/3b581e39-b5e2-4aa6-b7fe-2b7ee19d76fc)测试了一下0.9.7.post2，上述错误都修复了
![版本7](https://github.com/user-attachments/assets/de4ff29a-78aa-4825-a87d-046998f992bd)
[
![测试](https://github.com/user-attachments/assets/6e72a2b7-4435-423c-8f7a-5fcfb837b695)
](url)
，再试试罢

**Comment by Agnes4m** [comment]
没问题了，还有偷偷加你steam（）
